### DISCUSSION TITLE
Scope Rivet CSS

### DISCUSSION THREAD

**Discussion by scottanthonymurray** [indiana-university/rivet-source#424] [Feature and enhancement requests]
It’s easy to integrate Rivet at the start of a project, and that’s the general recommendation of UXO for product teams. Despite this, teams are still wanting to update parts of older products to Rivet standards as priorities allow. Rivet JS is relatively easy to integrate, because the usage of it is generally opt-in; for example, you add a `data-dropdown-toggle` attribute to initialize the Dropdown component. However, a lot of Rivet CSS is applied globally via element selectors, rather than class selectors. It can be convenient, because it reduces the weight of markup, but it causes frustration when it touches part of the interface that is not ready to be updated.

For example, two ESS products have implemented workarounds to implement the Rivet Header without affecting other parts of the apps.

@bw38 integrated it in iGPS. He imports `rivet.css` as a Less file in a custom scope, then does selective overrides of Rivet within that scope as needed.
* https://github.iu.edu/iu-uits-es/ess-sisaadm/blob/0a4a7bc5542f22068cab437520daf94699397da6/ui/src/appHeader/AppHeader.less
* https://github.iu.edu/iu-uits-es/ess-sisaadm/blob/0a4a7bc5542f22068cab437520daf94699397da6/ui/src/appHeader/AppHeader.jsx

@rileymg and @kmurodov integrated it in SAS (Student Appointment Scheduler) Advisor app.
* https://github.iu.edu/iu-uits-es/ess-sisaarex/blob/b36515783c494ab1c10a1d641914a295d179427d/README.md#upgrading-rivet-ux-library
* https://github.iu.edu/iu-uits-es/ess-sisaarex/commit/bde80c555dc742cba9c4c00c2116454769de485b
* https://github.iu.edu/iu-uits-es/ess-sisaarex/commit/ce3bdd9d1b6c989f7b85297c8bd2517ebf43044f

Both of these situations could be significantly simplified, if they only had to add, e.g., `.rvt-scope` (or `.rvt-global` or just `.rvt`) to the Header directly (or wherever they upgrade next time) and Rivet element selectors would only be applied within that container:

```html
<header class="rvt-scope rvt-header" role="banner">
    <a class="rvt-skip-link" href="#main-content">Skip to content</a>
    <div class="rvt-header__trident">
        <svg role="img" class="rvt-header__trident-logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 41 48" aria-describedby="iu-logo">
            <title id="iu-logo">Indiana University Logo</title>
            <rect width="41" height="48" fill="#900"/>
            <polygon points="24.59 12.64 24.59 14.98 26.34 14.98 26.34 27.78 22.84 27.78 22.84 10.9 24.59 10.9 24.59 8.57 16.41 8.57 16.41 10.9 18.16 10.9 18.16 27.78 14.66 27.78 14.66 14.98 16.41 14.98 16.41 12.64 8.22 12.64 8.22 14.98 9.97 14.98 9.97 30.03 12.77 33.02 18.16 33.02 18.16 36.52 16.41 36.52 16.41 39.43 24.59 39.43 24.59 36.52 22.84 36.52 22.84 33.02 28 33.02 31.01 30.03 31.01 14.98 32.78 14.98 32.78 12.64 24.59 12.64" fill="#fff"/>
        </svg>
    </div>
    <span class="rvt-header__title">
        <a href="#0">Application Title</a>
    </span>
</header>
```

***

To keep the benefits of the element selectors but still ensure Rivet is opt-in rather than forcefully global, all element selectors should be scoped under a class selector. Practically, that means a class name should be added to the topmost element or elements in which Rivet should affect.

```html
<html>
<body>
  <header>
    <div>App name</div>
  </header>
  <main class="rvt-scope">
    <h1>Main</h1>
    <p>Content</p>
  </main>
</body>
</html>
```

If you want Rivet to behave like it currently does, you just have to put the class on the HTML element. This is very minimal work to fix this breaking change.

```html
<html class="rvt-scope">
```

It may mean that selectors like in [`_base.scss`](https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/core/_base.scss):

```scss
abbr,
abbr[title] {
  border: none;
  text-decoration: none;
}
```

Need to be updated like this:

```scss
.rvt-scope {

  abbr,
  abbr&,
  abbr[title],
  abbr[title]& {
    border: none;
    text-decoration: none;
  }
}
```

And it would compile as:

```css
.rvt-scope abbr,
abbr.rvt-scope,
.rvt-scope abbr[title],
abbr[title].rvt-scope {
  border: none;
  text-decoration: none;
}
```

This would allow Rivet scope to be applied as a wrapper or to affected elements directly.

Top-level properties, such as what’s found in `html` and `body` element selectors, may need to be organized a little differently.

Current:

```scss
html {
  font-size: 100%; 
} 

html * { 
  box-sizing: border-box; 
} 

body { 
  color: $color-text; 
  font-family: $font-base; 
  margin: 0; 
  padding: 0; 
  line-height: 1.5; 
} 
```

Maybe update to:

```scss
.rvt-scope {
  color: $color-text; 
  font-family: $font-base; 
  font-size: 100%;
  line-height: 1.5;

  *,
  & {
    box-sizing: border-box; 
  }

  body,
  body& {
    margin: 0; 
    padding: 0;
  }
}
```

These are files with top-level element selectors that need to be scoped:
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/core/_base.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/libs/_normalize.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/components/_checkboxes.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/components/_inputs.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/components/_links.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/components/_lists.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/components/_radios.scss
* https://github.iu.edu/UITS/rivet-source/blob/v1.0.0/src/sass/components/_tables.scss
