### ISSUE TITLE
Possible pagination enhancements

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#12]
I have been using the pagination component in one of my apps and modified the SASS for that component to change a number of things:

* Add support for using buttons in a pagination component
  * You may want to consider adding similar styles for `span` elements but I haven't needed it yet
* Modified the border color so it matches other form controls
* Add `pointer-events: none;` to disabled links so they are not clickable
* Add `cursor: not-allowed;` to the `is-disabled` pagination item
* Change the way the overlapping borders work.  This makes it not show the left border except on the first child.  There were a couple of cases where the border would be double thick for some reason.

I'm not sure how many of these customizations might be worthwhile, but here's a copy of the modified SASS code in case these could be incorporated into Rivet core.

```scss
.rvt-pagination {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;

  &__item {

    a, button {
      background-color: white;
      border: 1px solid $color-black--700;
      border-left-width: 0;
      display: inline-block;
      margin-left: 0;
      min-width: $lg;
      /**
        * .75rem here makes the pagination the same height as text inputs
        * for consistency's sake.
        */
      padding: .75rem $sm;
      position: relative;
      text-decoration: none;
      transition: box-shadow .2s ease;
      z-index: map-get($z-index, z-100);
      user-select: none;
    }

    a:hover, button:hover {
        background-color: $color-black--100;
    }

    a:focus, button:focus {
        border-radius: inherit;
        /* stylelint-disable */
        box-shadow: 0 0 0 $xxs/2 $color-background,
                    0 0 0 $xxs $color-action;
        /* stylelint-enable */
        outline: none;
        z-index: map-get($z-index, z-1000);
    }

    a[aria-current="page"], button[aria-current="page"] {
      background-color: $color-action;
      border-color: $color-action;
      color: $color-background;
      /**
       * z-index hides the border overlap
       */
      z-index: map-get($z-index, z-200);
    }

    a[aria-disabled=true], button:disabled {
      color: $color-black--700;
      background-color: $color-black--100;
      pointer-events: none;

      &:focus {
          box-shadow: none;
      }
    }

    &:first-child a, &:first-child button {
      border-top-left-radius: $xxs;
      border-bottom-left-radius: $xxs;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
      border-left-width: 1px;
    }

    &:last-child a, &:last-child button {
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
      border-top-right-radius: $xxs;
      border-bottom-right-radius: $xxs;
    }

    /**
     * Disabled state
     */
    &.is-disabled, {
      cursor: not-allowed;
    }

  }
 
  &--small &__item {
    a, button {
        padding: .35rem .65rem;
    }
  }

}
```
