### ISSUE TITLE
Button labels should not wrap

### ISSUE THREAD

**Issue by basham** [indiana-university/rivet-source#128]
Button labels should never span more than one line of text. However, when resizing the viewport, sometimes things get a bit squished and it forces multi-word buttons to wrap. Prevent this from happening. Update to:

```css
.rvt-button {
  white-space: nowrap;
}
```
