### ISSUE TITLE
Badge text should not wrap

### ISSUE THREAD

**Issue by basham** [indiana-university/rivet-source#129]
Badges should never span more than one line of text. However, when resizing the viewport, sometimes things get a bit squished and it forces multi-word badges to wrap. Prevent this from happening. Update to:

```css
.rvt-badge {
  white-space: nowrap;
}
```
