### ISSUE TITLE
First box row should not have a top border

### ISSUE THREAD

**Issue by basham** [indiana-university/rivet-source#133]
The first box row in the [Box component](https://rivet.iu.edu/components/layout/box/) should not have a border, because the box provides the border. Right now, the top row bleeds past the area clipped by the border radius. To illustrate the point, I increased the border radius of this box and colored the rows as green:

![Demonstration of extra border](https://user-images.githubusercontent.com/347558/61243553-3877b880-a716-11e9-9416-156c9718bb39.png)

I think a solution could be to color the first row's border as transparent, rather than hiding the border, so that the rows maintain equivalent height. But this should be double-checked.

```css
/* This is probably the right solution. */
.rvt-box__row:first-child {
  background-color: transparent;
}

/* But maybe this. */
.rvt-box__row:first-child {
  border: none;
}

/* Or maybe only add the border if a row follows another row. */
.rvt-box__row + .rvt-box__row { ... }
```
