### ISSUE TITLE
Series Nav - Add visual parity for "last in series"

### ISSUE THREAD

**Issue by jameswilson** [indiana-university/rivet-source#752]
## Describe the bug

1.  ✅ When viewing a normal Series Nav with both the previous/next links, I see top and bottom borders but no left or right borders.

2.  ✅ When viewing a page that is the first item in a Series and there are no more previous items to show, I see top and bottom borders but no left or right borders.

3.  ❌ When viewing a page that is the last item in a Series and there are no more additional items to show, I see top and bottom borders <em>and a right border</em>.

    This is not an uncommon occurrence as this issue affects the most recent news article page in a typical reverse chronological Series Nav list. Site visitors will open the most recent news article more often than older articles.

## Expected behavior

The "last in series" scenario should look the same as the "first in series" scenario and the default Series Nav display, with no left or right borders.

## Relevant context (required)

Codepen demonstrating the issue and a workaround: 
https://codepen.io/jameswilson/pen/OJYmymV

<img width="921" alt="Screen Shot 2024-06-03 at 8 44 05 AM" src="https://github.com/indiana-university/rivet-source/assets/243532/5a67c958-c99c-4848-9bf7-03932f77efa9">

## Possible workarounds in website:

This issue can be fixed in custom code by adding `rvt-border-right-none` to `a.rvt-seriesnav__previous` in the specific scenario when there are no additional items to show for the "next" link, but this requires additional template logic.

<img width="894" alt="Screen Shot 2024-06-03 at 8 27 18 AM" src="https://github.com/indiana-university/rivet-source/assets/243532/9b2585bb-e6fb-43b9-acbc-bc42de802437">

It could also be done in custom CSS to override Rivet.

```
@media screen and (min-width: 46.25em) {
    .rvt-seriesnav__previous:only-child {
        border-right: 0;
        padding-right: 0;
    }
}
```

It seems a shame to require websites to implement additional code to solve this, when it's only a few lines of CSS that could be added to Rivet.

## Possible fixes in Rivet upstream:

This issue could be fixed in Rivet in two ways:

1. Instead of border-right on previous element, add border-right on "next" element, enabled via sibling selector.

```css
@media screen and (min-width: 46.25em) {
    .rvt-seriesnav__previous {
        flex-direction: row-reverse;
    }

    .rvt-seriesnav__previous ~ .rvt-seriesnav__next {
        border-left: 1px solid #e2e7e9;
        padding-left: 1.5rem
    }
}
```

2. Use the `:only-child` pseudo selector:

```css
@media screen and (min-width: 46.25em) {
    .rvt-seriesnav__previous {
        flex-direction: row-reverse;
        border-right: 1px solid #e2e7e9;
        padding-right: 1.5rem
    }

    .rvt-seriesnav__previous:only-child {
        border-right: 0;
        padding-right: 0;
    }
}
```

## Steps to reproduce

1.  Open https://rivet.iu.edu/components/series-nav/
2.  Click "Edit on codepen".
4.  Comment out or remove: `<a class="rvt-seriesnav__next" ...`
