### ISSUE TITLE
Segmented button group with only one button should have rounded corners

### ISSUE THREAD

**Issue by jameswilson** [indiana-university/rivet-source#782]
## Describe the bug
A segmented button group (`.rvt-button-segmented`) containing only one button incorrectly loses its rounded corners.

## Expected behavior
If a segmented button group contains only one button, that button should retain its standard rounded corners.

## Relevant context (required)

**Live demonstration:** [CodePen Example](https://codepen.io/jameswilson/pen/ByNLEvj)

**Visual:**
<img width="359" alt="Image" src="https://github.com/user-attachments/assets/8f59cbf7-4a5a-4b7c-afde-941316f1f25e" />

**Cause:**
When a button is the only child, it is both the `:first-child` and `:last-child`. The current CSS rules for these pseudo-classes in a segmented button context effectively cancel out the `border-radius`:

```css
/* Styles causing the issue */
.rvt-button-segmented .rvt-button:last-child {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    margin-left: -2px; /* Also problematic for a single button */
}
.rvt-button-segmented .rvt-button:first-child {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```

## Proposed resolution

Modify the existing CSS selectors to be exclusionary using `:not()`. This ensures the styles intended for modifying inner/end buttons in a multi-button group do not apply when a button is the sole child:

```css
/* Proposed exclusionary styles */
.rvt-button-segmented .rvt-button:not(:first-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    margin-left: -2px;
}
.rvt-button-segmented .rvt-button:not(:last-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```

With this change, if a `.rvt-button` is both the `:first-child` *and* `:last-child` (i.e., it's the only button), these exclusionary rules will not apply, allowing it to retain its default `border-radius` and avoiding the negative `margin-left`.

This resolves the issue with a pure CSS fix, avoiding the need for conditional server-side pre-render logic to manage button wrapping.

## Steps to reproduce

1. Go to https://rivet.iu.edu/components/button/?example=segmented-buttons
2. Click "Edit on Codepen" dropbutton.
3. Delete or comment out two of the three `<a class="rvt-button">`s.
4. Note square corners on the one remaining `<a class="rvt-button">`.

**Comment by jameswilson** [comment]
Documenting our temporary workaround as a Rivet style override until the fix lands upstream:

```css
/**
 * Retain rounded corners when a segmented button group has only one button.
 * 
 * @todo remove when https://github.com/indiana-university/rivet-source/issues/782 lands.
 */
.rvt-button-segmented .rvt-button:last-child,
.rvt-button-segmented .rvt-button:first-child {
    border-radius: .25rem;
    margin-left: 0;
}
.rvt-button-segmented .rvt-button:not(:first-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    margin-left: -2px;
}
.rvt-button-segmented .rvt-button:not(:last-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```
